const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}});
document.querySelector('#compare-range').addEventListener('input',e=>{const value=e.target.value;document.querySelector('#compare-top').style.clipPath=`inset(0 ${100-value}% 0 0)`;document.querySelector('#compare-line').style.left=value+'%'});
const sets={site:{title:'Projektų stebėsenos kadrai',description:'Pateikta projektų medžiaga. Objektų pavadinimai, datos ir atliktų darbų apimtis dar tikslinami.',images:[['lift.jpg','Vamzdyno kėlimas naktį'],['hero.jpeg','Statybvietė saulėlydžio metu'],['day.jpeg','Pramoninio pastato statyba dieną'],['build.jpeg','Pastato ir aplinkos įrengimo darbai']]},company:{title:'Įmonės turinio kryptis',description:'AI sugeneruota vizualinė koncepcija. Tai nėra įgyvendintas kliento projektas.',images:[['company.png','Įmonės turinio AI koncepcija']]},product:{title:'Produkto video kryptis',description:'AI sugeneruota vizualinė koncepcija. Tai nėra įgyvendintas kliento projektas.',images:[['product.png','Produkto AI koncepcija']]}};
const dialog=document.querySelector('#gallery');let active,index=0;
function render(){const item=active.images[index];document.querySelector('#gallery-title').textContent=active.title;document.querySelector('#gallery-image').src='assets/'+item[0];document.querySelector('#gallery-image').alt=item[1];document.querySelector('#gallery-description').textContent=active.description;document.querySelector('#counter').textContent=`${index+1} / ${active.images.length}`;document.querySelector('#prev').disabled=active.images.length===1;document.querySelector('#next').disabled=active.images.length===1;}
document.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{active=sets[b.dataset.gallery];index=0;render();dialog.showModal()}));
document.querySelector('#close-gallery').addEventListener('click',()=>dialog.close());
document.querySelector('#prev').addEventListener('click',()=>{index=(index-1+active.images.length)%active.images.length;render()});
document.querySelector('#next').addEventListener('click',()=>{index=(index+1)%active.images.length;render()});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelector('#brief').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const body=`VIDEO LAB — UŽKLAUSOS JUODRAŠTIS\n\nPaslauga: ${data.get('service')}\n\n${data.get('message')}\n\nŠis failas sukurtas lokaliai. Užklausa neišsiųsta.\n`;const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='videolab-uzklausa.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#status').textContent='Užklausos failas paruoštas atsisiųsti. Užklausa neišsiųsta.'});
